# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    # link to the about widget #
    url: '#about'
    weight: 10
  - name: Research
    # link to the research folder #
    url: research/
    weight: 20
  - name: Teaching
    # link to the teaching folder #
    url: 'teaching/'
    weight: 30
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  # - name: Projects
  #   url: '#projects'
  #   weight: 30
  - name: Publications
    # link to the publication folder #
    url: 'publication/'
    weight: 40
  - name: PHS Grad Writing Group
    url: 'event/'
    weight: 50
  # - name: Talks
  #   url: 'event/'
  #   weight: 50
  # - name: Test
  #   url: 'test/'
  #   weight: 100
  # - name: Courses
  #   url: courses/
  #   weight: 60
  # - name: Contact
  #   url: '#contact'
  #   weight: 70
